// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var explainOptions = []prompt.Suggest{
	prompt.Suggest{Text: "--api-version", Description: "Get different explanations for particular API version (API group/version)"},
	prompt.Suggest{Text: "--recursive", Description: "Print the fields of fields (Currently only 1 level deep)"},
}
